language: ruby
cache: bundler
matrix:
  fast_finish: true
rvm:
  - 2.7.5
  - 3.0.0
  - 3.1.0
  - 3.2.0
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
  - gemfiles/rails6.gemfile
  - gemfiles/rails7.gemfile
matrix:
  exclude:
    - rvm: 2.7.5
      gemfile: gemfiles/rails3.gemfile
script: bundle exec rspec
before_install:
  - gem install bundler